spring:
  flyway:
    enabled: false # flyway disable
  application:
    name: agit-common
  config:
    import:
      - company-constant.yml
#  jpa:
#    open-in-view: false # 영속성 유지 범위 지정 (default true)
#    database: mysql # db 연결정보
#    database-platform: org.hibernate.dialect.MySQL8Dialect # 데이터 플래폼을 지정
#    show-sql: true
#    hibernate:
#      ddl-auto: update
##      naming:
##        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
##        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#    properties:
#      hibernate:
#        format_sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console # available with web-console localhost:8090/h2-console
#  datasource:
#    driver-class-name: "org.h2.Driver"
#    url: "jdbc:h2:mem:agit"
#    username: "root"
#    password: "agit"
#  jpa:
#    show_sql: true
#    generate_ddl: false
#    hibernate:
#      ddl_auto: update # it will update the database schema based on the modifications in the domain model in our application
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: true



springdoc:
  api-docs:
    path: /api-docs

